ANNEAL_PRETRAINING: true
BATCH_SIZE: 32
BETA: 0.01
CHECKPT_PLOT: true
CLASS_PARAM: null
ROOT_RAW: Tutorials/TutorialData/
CLINIC_PARAM:
- extra_class_labels
DATA_TYPE:
  ANNO:
    FILE_RAW: ALY-2_SYS721_mappings.txt
    TYPE: ANNOTATION
  IMG:
    FILE_RAW: ALY-2_SYS721_mappings.txt
    FILTERING: NoFilt
    HEIGHT: 64
    SCALING: NoScaler
    TYPE: IMG
    WIDTH: 64
  PROTEOMICS:
    FILE_RAW: AM3_NO2_raw_cell.tsv
    FILTERING: NoFilt
    SCALING: MinMax
    TYPE: NUMERIC
DELTA_CLASS: 0.0
DELTA_PAIR: 0.7
DIM_RED_METH: UMAP
EPOCHS: 100
FIX_RANDOMNESS: all
GAMMA: 1.25
GLOBAL_SEED: 42
K_FILTER: 1000
LATENT_DIM_FIXED: 32
LR_FIXED: 0.001
MODEL_TYPE: x-modalix
PLOT_NUMERIC: true
PREDICT_SPLIT: all
PRETRAIN_EPOCHS: 30
PRETRAIN_TARGET_MODALITY: pretrain_image
RECONSTR_LOSS: MSE
ROOT_IMAGE: Tutorials/TutorialData/images/ALY-2_SYS721/
SPLIT:
- 0.7
- 0.2
- 0.1
TRAIN_TYPE: train
TRANSLATE: PROTEOMICS_to_IMG
VAE_LOSS: KL
RUN_ID: getting_started
